config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
    get 'users/mass_new', :to => 'users/registrations#mass_new'
    post 'users/mass_create', :to => 'users/registrations#mass_create'
    get 'users/admin_new', :to => 'users/registrations#admin_new'
    post 'users/admin_create', :to => 'users/registrations#admin_create'
    delete 'users/:id/destroy', :to => 'users/registrations#admin_destroy'
    get 'users/non_admins', :to => 'users/registrations#users_index'
    get 'users/admins', :to => 'users/registrations#admins_index'
    devise_for :users, :controllers => { :registrations => "users/registrations" }
    get 'users/:id', :to => 'users/registrations#show'
  end

  namespace "questions" do
    get ':id/without_answers', action: 'show_without_answers', as: 'show_without_answers'
    get 'questions_per_weightage', action: 'questions_per_weightage', as: 'questions_per_weightage'
    post ':id', action: 'update', as: 'update'
  end
  resources :questions 

  namespace "exams" do
    get 'timezones', action: 'timezones', as: 'timezones'
    post ':id/scheme', action: 'set_scheme', as: 'set_scheme'
    get ':id/scheme', action: 'show_scheme', as: 'show_scheme'
    post ':id/questions', action: 'set_questions', as: 'set_questions'
    get ':id/questions', action: 'select_questions', as: 'select_questions'
    post ':id/colleges', action: 'set_colleges', as: 'set_colleges'
    get ':id/colleges', action: 'select_colleges', as: 'select_colleges'
    get ':id/question_categories', action: 'question_categories', as: 'question_categories'
    post ':id', action: 'update', as: 'update'
  end
  resources :exams

  namespace "answer_sheets" do
    get ':id/review', action: 'review', as: 'review'
    get 'time_up', action: 'time_up', as: 'time_up'
    post ':id/change_ip', action: 'update_ip', as: 'update_ip'
    get 'change_ip', action: 'change_ip', as: 'change_ip'
    post ':id', action: 'update', as: 'update'
  end
  resources :answer_sheets

  namespace "colleges" do
    post ':id', action: 'update', as: 'update'
  end
  resources :colleges

  namespace "question_categories" do
    post ':id', action: 'update', as: 'update'
  end
  resources :question_categories

  get 'my_exams', to: 'exams#my_exams'

  root to: "welcome#welcome"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Infibeam Online Screening</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
        	<% if can? :manage, :site %>
        	<%= link_to "Home", exams_path, :method => "get" %>
        	<% elsif can? :give, :exam %>
        	<%= link_to "My Exams", my_exams_path, :method => "get" %>
        	<% end %>
        </li>
        <% if can? :manage, :site %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Exams <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><%= link_to "Index", exams_path, :method => "get" %></li>
          	<li class="divider"></li>
            <li><%= link_to "New Exam", new_exam_path, :method => "get" %></li>
            <li class="divider"></li>
            <li><%= link_to "Results", answer_sheets_path, :method => "get" %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Questions <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><%= link_to "Index", questions_path, :method => "get" %></li>
          	<li class="divider"></li>
            <li><%= link_to "New Question", new_question_path, :method => "get" %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><%= link_to "Index", users_path, :method => "get" %></li>
          	<li class="divider"></li>
          	<li><%= link_to "New Admin", users_admin_new_path, :method => "get" %></li>
          	<li class="divider"></li>
            <li><%= link_to "New Users", users_mass_new_path, :method => "get" %></li>
            <li class="divider"></li>
            <li><%= link_to "Change User IP", answer_sheets_change_ip_path, :method => "get" %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Colleges <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Index", colleges_path, :method => "get" %></li>
            <li class="divider"></li>
            <li><%= link_to "New College", new_college_path, :method => "get" %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="glyphicon glyphicon-user"></i> <%= current_user.first_name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Account Settings", edit_user_registration_path, :method => "get" %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => "delete" %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineScreening</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app='onlineScreening' style="padding-top: 60px">

<%= render 'layouts/header' %>

<% if notice %>	
<div class="alert alert-success">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<strong>Note!</strong> <%= notice %>	
</div>
<% end %>

<% if alert %>	
<div class="alert alert-warning">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<strong>Error!</strong> <%= alert %>	
</div>
<% end %>

<%= yield %>

</body>
</html>